spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: macbookpro
    password: 19801980
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    time-zone: Asia/Tashkent


app-security:
  token:
    access-exp: 180000
    refresh-exp: 86400000
    secret: bu_secret_key_uzunligi_kamida_32_byte_boliswqewqewqewq

application:
  sync-db: true



