  # Message broker

  # malumotni yaxlitliga
  # async
  # masshtablilik (pub/sub)

  # client -> service1 ->  (mb(data))->  service2 (notfy service)

  #

  spring:
    rabbitmq:
      port: 5672
      host: localhost
      username: guest
      password: guest
