spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: macbookpro
    password: 19801980
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  jackson:
    time-zone: Asia/Tashkent

  profiles:
    active: prod,telegram


springdoc:
  swagger-ui:
    path: /









